project:
  type: website
  output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/dbrentecon
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=-0oqdtsAAAAJ&hl=en
        
execute:
  freeze: false

format:
  html:
    theme: cosmo
    toc: false
    css: my-css.css
